### Add Fournisseur
POST http://localhost:8080/tricol_app_war_exploded/api/v1/fournisseurs
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "societe": "ACME Supplies",
  "address": "123 Market St",
  "contact": "contact@acme.example",
  "email": "for@for.com",
  "telephone": "+1-111-1111",
  "ville": "rabat",
  "ice": "AA45GH45CF78"
}
###{
###  "societe": "ACME Supplies",
###  "address": "123 Market St",
###  "contact": "contact@acme.example",
###  "email": "for@for.com",
###  "telephone": "+1-555-0100",
###  "ville": "rabat",
###  "ice": "AA45GH45CF78"
###}

### Get List of Fournisseurs

GET http://localhost:8080/tricol_app_war_exploded/api/v1/fournisseurs

### Get Fournisseur By Id

GET http://localhost:8080/tricol_app_war_exploded/api/v1/fournisseurs/1

### Update Fournisseur By Id

PUT http://localhost:8080/tricol_app_war_exploded/api/v1/fournisseurs/1
Content-Type: application/json; charset=utf-8
Accept: application/json

{
  "societe": "ACME Update",
  "address": "123 Market Update",
  "contact": "App 48 rue 122",
  "email": "update@update.com",
  "telephone": "+0-000-0000",
  "ville": "update",
  "ice": "AA45G125UPDATE"
}

### Delete Fournisseur

DELETE http://localhost:8080/tricol_app_war_exploded/api/v1/fournisseurs/2






